### ISSUE TITLE
Running without Hass.io

### ISSUE THREAD

**Issue by eavanvalkenburg** [hunterjm/hassio-addons#10]
Hi Jason, I was working on building something directly in HA for my xbox one, and ran into this version, but since I don't run hass.io but just run HA directly on Linux I was wondering what the restfull server is doing in between HA and the Xbox and if we need that, what exactly does that thing do?

**Comment by hunterjm** [comment]
The smart glass library is written using gevent, and the protocol is very chatty. I tried integrating directly in HA initially, but the gevent loop kept getting starved. You can try to re-write the protocol using asyncio, but that was more effort than it was worth, so we wrapped it behind a stand-alone server. The FireTV component does something very similar.

You can still pip install xbox-rest-server on your Linux server and run it separately, then just copy the component here for everything to work. This addon just makes it easy for Hass.io.
