### ISSUE TITLE
State is always unknown when on

### ISSUE THREAD

**Issue by Newlance** [hunterjm/hassio-addons#11]
It looks like STATE_ON was never implemented in your xbone.py, was this intentional?
theoretically the state will change when media is playing, but I'm really tempted to change almost all the instances of STATE_UNKNOWN with STATE_ON

**Comment by tuxuser** [comment]
Please refer to PR #6 for the discussion about STATES

**Comment by hunterjm** [comment]
I just merged some changes into the develop branch that addresses this.  You can test that component out.

**Comment by martimarkov** [comment]
@hunterjm Hey, I'm having the same issue on version 1.1.0. There are 2 Xbox at my house. One of them is offline and not connected/paired to my account.
