### ISSUE TITLE
Allow specifying the IP address of the console

### ISSUE THREAD

**Issue by vogelfreiheit** [hunterjm/hassio-addons#15]
When running in isolated subnets (through VLANs), broadcasts won't fly. However, routing and firewall rules make it possible to reach the console over at a different subnet. Unfortunately there is no way apparently to input the address of the console. I know the smartglass component permits this parameter for discovery but I don't see anywhere a method that exposes it from YAML in the add-on for HA.

https://media.readthedocs.org/pdf/xbox-smartglass-core-python/stable/xbox-smartglass-core-python.pdf

**Comment by hunterjm** [comment]
There are two open PR's that will help resolve this. https://github.com/OpenXbox/xbox-smartglass-rest-python/pull/19 and https://github.com/OpenXbox/xbox-smartglass-rest-python/pull/16.

Depending on which one the maintainer of the library goes with, I will update the custom component to allow specifying the IP of the console.

**Comment by hunterjm** [comment]
Implemented here: https://github.com/hunterjm/hassio-addons/commit/1c65891f1bb4e7b10155b1938058903cb5a16c81

**Comment by vogelfreiheit** [comment]
How can I specify the develop branch when adding the repo to Hassio?

**Comment by hunterjm** [comment]
You shouldn’t. The new version of the server needs to be published, then I will release a new version of the addon. It should be done in less than a week.

**Comment by tuxuser** [comment]
This issue is solved with PR #18

**Comment by hunterjm** [comment]
Available in 1.1.0
