### ISSUE TITLE
TensorFlow qemux86-64 Architecture

### ISSUE THREAD

**Issue by emouawad** [hunterjm/hassio-addons#42]
Does this or Will it be able to support qemux86-64? 

It installed just fine - but HomeAssistant is now crashing when i add image_processing configuration - I am wondering what's wrong my configs or this isn't supported?

**Comment by philgree** [comment]
Me too :(

I'm also qemux86-64 and am using 0.92. HA loads fine without image_processing config but fails to bring up UI once image_processing in introduced into configuration.yaml. 

home-assistant.log says:

> 2019-04-27 09:57:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

Once image processing is removed from configuration.yaml, HA restarts without issue.

**Comment by philgree** [comment]
Interestingly, without image processing a bunch of other warning errors (breaking changes, custom updater, influxdb) were supressed. Once I dealt with each of those the problem remained and no additional errors were reported in home_assistant.log but a tensorflow related python error came up on the console (refer screenshot).

![image](https://user-images.githubusercontent.com/22829086/56839554-26d10280-68d7-11e9-81b7-da4841290162.png)

**Comment by HITChris** [comment]
Seeing the same thing here. Any update from @hunterjm ?

**Comment by JBelinchon** [comment]
I got it working using this docker container: homeassistant/amd64-base-python:3.7 and then following this [instructions](https://github.com/hunterjm/hassio-addons/commit/6cd16290c9fe5d67ba8aa0f704d956bcbb0b7e83):

**Comment by nic0dk** [comment]
> I got it working using this docker container: homeassistant/amd64-base-python:3.7 and then following this [instructions](https://github.com/hunterjm/hassio-addons/commit/6cd16290c9fe5d67ba8aa0f704d956bcbb0b7e83):

Hi JBelinchon, so you are not running hassio, is that correct?
