### ISSUE TITLE
Issues on HA 0.101.2

### ISSUE THREAD

**Issue by richmansfield** [hunterjm/hassio-addons#51]
After installing the home assistant integration as a Hass.io repoistory as per instructions, I recieve a 'Integration 'xboxone' not found.'

I have tried manually creating some of the missing files from the custom components folder:
__init.py__ - containing a comment only
manifest.py - containing minimal manifest file
services.yaml - empty file

I have also tried updating media_player.py to move from VOLUME_STEP to VOLUME_SET - but still the platform fails silently without logging any errors.

Seems the plugin may need other updates to bring it inline with later Home Assistant versions - is anyone using this plugin with newer releases?

**Comment by richmansfield** [comment]
Managed to get this to load after some more tweaks, seems the __ init.py ___ and manifest.py was all that was needed. Marked as closed for now unless there are other issues.

**Comment by thellosd** [comment]
> Managed to get this to load after some more tweaks, seems the __ init.py ___ and manifest.py was all that was needed. Marked as closed for now unless there are other issues.

Question regarding your custome_components folder. You stated you only needed the __init.py__ and manifest.py files. What of the media_player.py file?
